baseURL = "https://nymtech.net/docs/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Nym Docs"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
# publishDir = "../nym-www/build/docs/"

[params]
  # editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Nym Documentation for mixnodes, coconut credentials, validators, and privacy-related systems."
  author = "Nym Team"
  stable = "0.10.1"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableInlineCopyToClipBoard = true
  disableLanguageSwitchingButton = true
  disableNextPrev = false
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Website"
url = "https://nymtech.net"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-medium'></i> Blog"
url = "https://medium.com/nymtech"
weight = 15

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/nymtech/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-key'></i> Developer Chat"
url = "https://nymtech.net/docs/overview/links/"
weight = 25

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
identifier = "tw"
url = "https://twitter.com/nymproject/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-telegram'></i> Telegram"
identifier = "tg"
url = "https://t.me/nymchan"
weight = 40
