baseURL = "https://nymtech.net/docs/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Nym Docs"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
# publishDir = "../nym-www/build/docs/"

[params]
# GENERAL
description = "Nym Documentation for mixnodes, coconut credentials, validators, and privacy-related systems."
author = "Nym Team"
showVisitedLinks = false
disableBreadcrumb = false
disableInlineCopyToClipBoard = true
disableLanguageSwitchingButton = true
disableNextPrev = false
themeVariant = "blue" # Change default color scheme with a variant one. Can be "red", "blue", "green".
enableGitInfo = true

# TESTNET SPECIFIC VARS
testnetName = "Milhon"
testnetNameLowercase = "milhon"
testnetToken = "PUNK"
bech32Prefix = "punk"

# BINARY VERSIONS
stable = "0.10.2" # TODO remove after all individual binaries have their own version
mixnodestable = "0.10.2"
validatorstable = "0.10.2"
gatewaystable = "0.10.1"
requesterstable = "0.10.2"
clientstable = "0.10.1"
socks5stable = "0.10.1"
validatorapistable = "0.10.1"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
# expiryDate = ["expiryDate"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Website"
url = "https://nymtech.net"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-medium'></i> Blog"
url = "https://medium.com/nymtech"
weight = 15

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/nymtech/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-key'></i> Developer Chat"
url = "https://nymtech.net/docs/overview/links/"
weight = 25

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
identifier = "tw"
url = "https://twitter.com/nymproject/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-telegram'></i> Telegram"
identifier = "tg"
url = "https://t.me/nymchan"
weight = 40
